services:
  db:
    image: postgres:14-alpine
    container_name: marketlab-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .deploy.env
    environment:
      - POSTGRES_PASSWORD=pass
    command: postgres -c 'max_connections=200'
    ports:
      - 5433:5432
  marketlab:
    image: marketlab
    container_name: marketlab
    restart: always
    env_file:
      - .deploy.env
    ports:
      - "3000:3000"


volumes:
  postgres_data:


